    <div class="mtraUsr"><div></div><button id='cerrar' class='btn' type="button">Cerrar</button></div>
    <?php
        if ($this->datos) {
            echo "
            <!-- Content Row -->
            <div class='row'>";
            foreach($this->datos as $r) {
                $cedid = $r['idusr'];
                $rasoc = mb_convert_encoding( htmlspecialchars( $r['usuario'], ENT_QUOTES, 'UTF-8' ), 'HTML-ENTITIES', 'UTF-8' );
                $categ = $r['estatus'];
                echo "
                    <input type='hidden' id='$cedid' value='$categ'>
                    <div class='col-xl-3 col-md-4 mb-2 mt-2'>
                        <div class='card border-left-primary shadow h-100 py-2'>
                            <div class='card-body'>
                                <div class='row no-gutters align-items-center'>
                                    <div class='col mr-2'>
                                        <div class='text-xs font-weight-bold text-primary text-uppercase mb-1'>$cedid</div>
                                        <div class='h5 mb-0 font-weight-bold text-gray-800'>" . $rasoc . "</div>
                                    </div>
                                    <div class='col-auto' id='sUser'>
                                        <img src='" . $_Params['ruta_img'] . "user64.png' id='$cedid'>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                ";
            }
            echo "
            </div>";
        }
    ?>
    
</div>